nome = str(input('Digite seu nome completo:')).strip()
print('Analisando o seu nome...')
nomeM= nome.upper()
print('Seu nome em maiúscula é {}'.format(nomeM))
nomem= nome.lower()
print('Seu nome em minúscula é {}'.format(nomem))
print('Seu nome ao todo tem {} letras'.format(len(nome)-nome.count(' ')))
#print('Seu primeiro nome tem {}'.format(nome.find(' ')))
separa = nome.split()
print('Seu primeiro nome é {} e tem {} letras'.format(separa[0], len(separa[0])))